### ISSUE TITLE
Question about `genrand_range`

### ISSUE THREAD

**Issue by parnalte** [esheldon/pymangle#19]
Hi,

I have a question about the intended usage of the function `genrand_range`. From the docs I understood that, for small masks, one would want to choose a box small enough to speed the calculation up but large enough to contain the full mask.

However, when I call the function in this way I get a `ValueError: no corners are contained within mask`. This is because the code requires that at least one of the corners of the box is contained in the mask: https://github.com/esheldon/pymangle/blob/0aeec8ca7a406a9c0f6f5500a28a2f9226bd4f96/pymangle/_mangle.c#L1589-L1595

However, if one of the corners is inside the mask, I understand that it is no longer possible to generate random points from the full mask (only from the part of the mask that overlaps with the box). So, is this a bug or am I misunderstanding the intended usage of the function?

Thanks,
Pablo.

**Comment by esheldon** [comment]
Good point, I think this is a bug.

**Comment by parnalte** [comment]
Great. I think it is solved now. Thanks.
