### ISSUE TITLE
seg fault reading file

### ISSUE THREAD

**Issue by esheldon** [esheldon/pymangle#4]
This is an issue sent to me by Paniez Paykari.  The file is attached (made the extension .txt so github would be happy)

The seg fault actually comes when using the mask, e.g. getting the weight for an ra,dec point.

It was created using.
```
pixelize
snap
balkanize
unify
```
[testPaniez.txt](https://github.com/esheldon/pymangle/files/427014/testPaniez.txt)

**Comment by esheldon** [comment]
The pixel scheme in this file is set to `-1s` which is not valid.

**Comment by esheldon** [comment]
there is also a bug in pymangle; it should ignore this -1s pixelization (slow lookups) or throw an error.

**Comment by esheldon** [comment]
I think the right thing to do is treat something like "-1s" as equivalent to unpixelized.

**Comment by esheldon** [comment]
I put a fix in 74995de29590e9f094af19ad27bddc0055594a10 

negative resolution is treated as  unpixelized

**Comment by Paniez** [comment]
Hi Erin, 
Thank you for fixing the bug. It works perfectly fine now. Excellent. 
Paniez

**Comment by esheldon** [comment]
OK, closing.
